name: Gated Destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to destroy (dev or staging)'
        required: true
        type: choice
        options:
          - dev
          - staging

permissions:
  id-token: write
  contents: read

env:
  TF_VERSION: 1.8.5
  TF_INFRA_DIR: infra
  AWS_REGION: us-east-1

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    defaults:
      run:
        working-directory: ${{ env.TF_INFRA_DIR }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.CI_RUNNER_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Confirmation
        run: |
          echo "Destroying: ${{ github.event.inputs.environment }}"

      - name: Terraform Init
        run: terraform init -backend-config=envs/${{ github.event.inputs.environment }}/backend-${{ github.event.inputs.environment }}.hcl

      - name: Terraform Destroy
        run: terraform destroy -var-file=envs/${{ github.event.inputs.environment }}/${{ github.event.inputs.environment }}.tfvars -auto-approve
